In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("india_bike_sales_300_records.csv")

In [3]:
df

,Sale_ID,Sale_Date,Bike_Model,City,Units_Sold,Revenue_INR
0,BS001,2025-01-02,Yamaha FZ,Mumbai,4,540000
1,BS002,2025-01-03,Yamaha FZ,Delhi,9,1215000
2,BS003,2025-01-04,Honda Shine,Pune,5,450000
3,BS004,2025-01-05,Hero Splendor,Mumbai,18,1530000
4,BS005,2025-01-06,Royal Enfield Classic,Mumbai,14,2940000
...,...,...,...,...,...,...
295,BS296,2025-10-24,Royal Enfield Classic,Mumbai,10,2100000
296,BS297,2025-10-25,Honda Shine,Delhi,10,900000
297,BS298,2025-10-26,Bajaj Pulsar,Bengaluru,6,720000
298,BS299,2025-10-27,Hero Splendor,Delhi,18,1530000
299,BS300,2025-10-28,Bajaj Pulsar,Mumbai,2,240000

In [4]:
df.head()

  Sale_ID   Sale_Date             Bike_Model    City  Units_Sold  Revenue_INR
0   BS001  2025-01-02              Yamaha FZ  Mumbai           4       540000
1   BS002  2025-01-03              Yamaha FZ   Delhi           9      1215000
2   BS003  2025-01-04            Honda Shine    Pune           5       450000
3   BS004  2025-01-05          Hero Splendor  Mumbai          18      1530000
4   BS005  2025-01-06  Royal Enfield Classic  Mumbai          14      2940000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sale_ID      300 non-null    object
 1   Sale_Date    300 non-null    object
 2   Bike_Model   300 non-null    object
 3   City         300 non-null    object
 4   Units_Sold   300 non-null    int64
 5   Revenue_INR  300 non-null    int64
dtypes: int64(2), object(4)
memory usage: 14.2+ KB

In [7]:
df.describe(include='all')

       Sale_ID   Sale_Date Bike_Model    City  Units_Sold   Revenue_INR
count      300         300        300     300  300.000000  3.000000e+02
unique     300         300          6       6         NaN           NaN
top      BS001  2025-01-02  Yamaha FZ  Mumbai         NaN           NaN
freq         1           1         58      59         NaN           NaN
mean       NaN         NaN        NaN     NaN   10.920000  1.428500e+06
std        NaN         NaN        NaN     NaN    5.563281  9.004358e+05
min        NaN         NaN        NaN     NaN    1.000000  8.500000e+04
25%        NaN         NaN        NaN     NaN    7.000000  7.200000e+05
50%        NaN         NaN        NaN     NaN   11.000000  1.320000e+06
75%        NaN         NaN        NaN     NaN   16.000000  1.890000e+06
max        NaN         NaN        NaN     NaN   20.000000  4.200000e+06

In [10]:
df.isnull().sum()

Sale_ID        0
Sale_Date      0
Bike_Model     0
City           0
Units_Sold     0
Revenue_INR    0
dtype: int64

In [11]:
df.columns=df.columns.str.lower()

In [13]:
df.columns

Index(['sale_id', 'sale_date', 'bike_model', 'city', 'units_sold',
       'revenue_inr'],
      dtype='object')

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.head(5)

  sale_id   sale_date             bike_model    city  units_sold  revenue_inr
0   BS001  2025-01-02              Yamaha FZ  Mumbai           4       540000
1   BS002  2025-01-03              Yamaha FZ   Delhi           9      1215000
2   BS003  2025-01-04            Honda Shine    Pune           5       450000
3   BS004  2025-01-05          Hero Splendor  Mumbai          18      1530000
4   BS005  2025-01-06  Royal Enfield Classic  Mumbai          14      2940000

In [16]:
df['sale_date']=pd.to_datetime(df['sale_date'])

In [17]:
df['sale_date']

0     2025-01-02
1     2025-01-03
2     2025-01-04
3     2025-01-05
4     2025-01-06
         ...
295   2025-10-24
296   2025-10-25
297   2025-10-26
298   2025-10-27
299   2025-10-28
Name: sale_date, Length: 300, dtype: datetime64[ns]

In [18]:
df['month']=df['sale_date'].dt.month_name()

In [20]:
df[['month']]

       month
0    January
1    January
2    January
3    January
4    January
..       ...
295  October
296  October
297  October
298  October
299  October

[300 rows x 1 columns]

In [33]:
df.groupby('city',as_index=False)['revenue_inr'].sum().sort_values(by='revenue_inr',ascending=False)

        city  revenue_inr
4     Mumbai     81890000
2      Delhi     73735000
1    Chennai     72045000
0  Bengaluru     69560000
3  Hyderabad     66235000
5       Pune     65085000

In [35]:
df.groupby('bike_model',as_index=False)['revenue_inr'].sum().sort_values(by='revenue_inr',ascending=False)

              bike_model  revenue_inr
3  Royal Enfield Classic    120540000
5              Yamaha FZ     88020000
4             TVS Apache     64540000
0           Bajaj Pulsar     60120000
2            Honda Shine     51300000
1          Hero Splendor     44030000

In [37]:
df.groupby('bike_model',as_index=False)['units_sold'].count()

              bike_model  units_sold
0           Bajaj Pulsar          49
1          Hero Splendor          45
2            Honda Shine          54
3  Royal Enfield Classic          50
4             TVS Apache          44
5              Yamaha FZ          58

In [43]:
from sqlalchemy import create_engine

#mysql connection
user_name ="root"
password ="root"
host ="localhost"
port ="3306"
database ="bike_sales"

engine =create_engine(f"mysql+pymysql://{user_name}:{password}@{host}:{port}/{database}")

table_name ="bike"
df.to_sql(table_name, engine, if_exists="replace", index=False)
pd.read_sql("select*from bike limit 5;",engine)

,sale_id,sale_date,bike_model,city,units_sold,revenue_inr,month
0,BS001,2025-01-02,Yamaha FZ,Mumbai,4,540000,January
1,BS002,2025-01-03,Yamaha FZ,Delhi,9,1215000,January
2,BS003,2025-01-04,Honda Shine,Pune,5,450000,January
3,BS004,2025-01-05,Hero Splendor,Mumbai,18,1530000,January
4,BS005,2025-01-06,Royal Enfield Classic,Mumbai,14,2940000,January